services:
  postgres:
    ports:
      - "5433:5432"

  redis:
    ports:
      - "6380:6379"

  mlflow:
    ports:
      - "5001:5000"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
